package courierDM;
// default package
// Generated Jun 22, 2017 11:34:38 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * BestRoute generated by hbm2java
 */
@Entity
@Table(name = "best_route", catalog = "courier")
public class BestRoute implements java.io.Serializable {

	private Integer routeId;
	private int packageId;
	private String routeFrom;
	private String route;
	private int totalMiles;

	public BestRoute() {
	}

	public BestRoute(int packageId, String routeFrom, String route, int totalMiles) {
		this.packageId = packageId;
		this.routeFrom = routeFrom;
		this.route = route;
		this.totalMiles = totalMiles;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "route_id", unique = true, nullable = false)
	public Integer getRouteId() {
		return this.routeId;
	}

	public void setRouteId(Integer routeId) {
		this.routeId = routeId;
	}

	@Column(name = "package_id", nullable = false)
	public int getPackageId() {
		return this.packageId;
	}

	public void setPackageId(int packageId) {
		this.packageId = packageId;
	}

	@Column(name = "route_from", nullable = false, length = 10)
	public String getRouteFrom() {
		return this.routeFrom;
	}

	public void setRouteFrom(String routeFrom) {
		this.routeFrom = routeFrom;
	}

	@Column(name = "route", nullable = false, length = 100)
	public String getRoute() {
		return this.route;
	}

	public void setRoute(String route) {
		this.route = route;
	}

	@Column(name = "total_miles", nullable = false)
	public int getTotalMiles() {
		return this.totalMiles;
	}

	public void setTotalMiles(int totalMiles) {
		this.totalMiles = totalMiles;
	}

}
