package courierDM;
// default package
// Generated Jun 11, 2017 6:09:55 PM by Hibernate Tools 4.3.1.Final

import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.JoinColumn;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * DeliveryTicket generated by hbm2java
 */
@Entity
@Table(name = "delivery_ticket", catalog = "courier")
public class DeliveryTicket implements java.io.Serializable {

	private Integer ticketId;
	private int senderId;
	private int receiverId;
	private int courierId;
	private Date estimatedPickup;
	private Date estimatedDelivery;
	private Date actualPickup;
	private Date actualDelivery;
	private int estimatedMiles;
	private int estimatedCost;
	private int billlTo;
	private int billed;
	private int delivered;
	private int picked;
	private Date transactionDate;
	private int packageId;
	private int driverBonus;
	
	
	private Courier courier;
	private Client sender;
	
	private Client receiver;

	private Client billTo;

	public DeliveryTicket() {
	}

	public DeliveryTicket(int senderId, int receiverId, int courierId, Date estimatedPickup, Date estimatedDelivery,
			Date actualPickup, Date actualDelivery, int estimatedMiles, int estimatedCost, int billlTo, int billed,
			int delivered, int picked, Date transactionDate, int packageId, int driverBonus) {
		this.senderId = senderId;
		this.receiverId = receiverId;
		this.courierId = courierId;
		this.estimatedPickup = estimatedPickup;
		this.estimatedDelivery = estimatedDelivery;
		this.actualPickup = actualPickup;
		this.actualDelivery = actualDelivery;
		this.estimatedMiles = estimatedMiles;
		this.estimatedCost = estimatedCost;
		this.billlTo = billlTo;
		this.billed = billed;
		this.delivered = delivered;
		this.picked = picked;
		this.transactionDate = transactionDate;
		this.packageId = packageId;
		this.driverBonus = driverBonus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ticket_id", unique = true, nullable = false)
	public Integer getTicketId() {
		return this.ticketId;
	}

	public void setTicketId(Integer ticketId) {
		this.ticketId = ticketId;
	}

	@Column(name = "sender_id", nullable = false)
	public int getSenderId() {
		return this.senderId;
	}

	public void setSenderId(int senderId) {
		this.senderId = senderId;
	}

	@Column(name = "receiver_id", nullable = false)
	public int getReceiverId() {
		return this.receiverId;
	}

	public void setReceiverId(int receiverId) {
		this.receiverId = receiverId;
	}

	@Column(name = "courier_id", nullable = false)
	public int getCourierId() {
		return this.courierId;
	}

	public void setCourierId(int courierId) {
		this.courierId = courierId;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "estimated_pickup", nullable = false, length = 8)
	public Date getEstimatedPickup() {
		return this.estimatedPickup;
	}

	public void setEstimatedPickup(Date estimatedPickup) {
		this.estimatedPickup = estimatedPickup;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "estimated_delivery", nullable = false, length = 8)
	public Date getEstimatedDelivery() {
		return this.estimatedDelivery;
	}

	public void setEstimatedDelivery(Date estimatedDelivery) {
		this.estimatedDelivery = estimatedDelivery;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "actual_pickup", nullable = false, length = 8)
	public Date getActualPickup() {
		return this.actualPickup;
	}

	public void setActualPickup(Date actualPickup) {
		this.actualPickup = actualPickup;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "actual_delivery", nullable = false, length = 8)
	public Date getActualDelivery() {
		return this.actualDelivery;
	}

	public void setActualDelivery(Date actualDelivery) {
		this.actualDelivery = actualDelivery;
	}

	@Column(name = "estimated_miles", nullable = false)
	public int getEstimatedMiles() {
		return this.estimatedMiles;
	}

	public void setEstimatedMiles(int estimatedMiles) {
		this.estimatedMiles = estimatedMiles;
	}

	@Column(name = "estimated_cost", nullable = false)
	public int getEstimatedCost() {
		return this.estimatedCost;
	}

	public void setEstimatedCost(int estimatedCost) {
		this.estimatedCost = estimatedCost;
	}

	@Column(name = "billl_to", nullable = false)
	public int getBilllTo() {
		return this.billlTo;
	}

	public void setBilllTo(int billlTo) {
		this.billlTo = billlTo;
	}

	@Column(name = "billed", nullable = false)
	public int getBilled() {
		return this.billed;
	}

	public void setBilled(int billed) {
		this.billed = billed;
	}

	@Column(name = "delivered", nullable = false)
	public int getDelivered() {
		return this.delivered;
	}

	public void setDelivered(int delivered) {
		this.delivered = delivered;
	}

	@Column(name = "picked", nullable = false)
	public int getPicked() {
		return this.picked;
	}

	public void setPicked(int picked) {
		this.picked = picked;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "transaction_date", nullable = false, length = 10)
	public Date getTransactionDate() {
		return this.transactionDate;
	}

	public void setTransactionDate(Date transactionDate) {
		this.transactionDate = transactionDate;
	}

	@Column(name = "package_id", nullable = false)
	public int getPackageId() {
		return this.packageId;
	}

	public void setPackageId(int packageId) {
		this.packageId = packageId;
	}

	@Column(name = "driver_bonus", nullable = false)
	public int getDriverBonus() {
		return this.driverBonus;
	}

	public void setDriverBonus(int driverBonus) {
		this.driverBonus = driverBonus;
	}

	@ManyToOne 
	@JoinColumn(name="courier_id",  insertable=false, updatable=false)
	public Courier getCourier() {
		return courier;
	}

	public void setCourier(Courier courier) {
		this.courier = courier;
	}

	@ManyToOne 
	@JoinColumn(name="sender_id",  insertable=false, updatable=false)
	public Client getSender() {
		return sender;
	}

	public void setSender(Client sender) {
		this.sender = sender;
	}

	
	@ManyToOne 
	@JoinColumn(name="receiver_id",  insertable=false, updatable=false)
	public Client getReceiver() {
		return receiver;
	}

	public void setReceiver(Client receiver) {
		this.receiver = receiver;
	}

	@ManyToOne 
	@JoinColumn(name="billl_to",  insertable=false, updatable=false)
	public Client getBillTo() {
		return billTo;
	}

	public void setBillTo(Client billTo) {
		this.billTo = billTo;
	}
}
