package courierDM;
// default package
// Generated Jun 18, 2017 8:50:54 AM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Map generated by hbm2java
 */
@Entity
@Table(name = "map", catalog = "courier")
public class Map implements java.io.Serializable {

	private Integer id;
	private int street;
	private String ave;
	private String edgeName;
	private String direction;

	public Map() {
	}

	public Map(int street, String ave, String edgeName, String direction) {
		this.street = street;
		this.ave = ave;
		this.edgeName = edgeName;
		this.direction = direction;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "street", nullable = false)
	public int getStreet() {
		return this.street;
	}

	public void setStreet(int street) {
		this.street = street;
	}

	@Column(name = "ave", nullable = false, length = 5)
	public String getAve() {
		return this.ave;
	}

	public void setAve(String ave) {
		this.ave = ave;
	}

	@Column(name = "edge_name", nullable = false, length = 50)
	public String getEdgeName() {
		return this.edgeName;
	}

	public void setEdgeName(String edgeName) {
		this.edgeName = edgeName;
	}

	@Column(name = "direction", nullable = false, length = 5)
	public String getDirection() {
		return this.direction;
	}

	public void setDirection(String direction) {
		this.direction = direction;
	}

}
